---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "my-release-consul-pdb"
  labels:
    app: "consul"
    chart: consul-5.3.6
    release: "my-release"
    heritage: "Tiller"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      heritage: "Tiller"
      release: "my-release"
      chart: consul-5.3.6
---
apiVersion: v1
kind: Service
metadata:
  name: "my-release-consul"
  labels:
    app: "consul"
    chart: consul-5.3.6
    release: "my-release"
    heritage: "Tiller"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: rpc
    port: 8400
  - name: serflan-tcp
    protocol: "TCP"
    port: 8301
  - name: serflan-udp
    protocol: "UDP"
    port: 8301
  - name: server
    port: 8300
  - name: consuldns-tcp
    port: 8600
  - name: consuldns-udp
    protocol: "UDP"
    port: 8600
  clusterIP: None
  selector:
    app: "consul"
    release: "my-release"
---
apiVersion: v1
kind: Service
metadata:
  name: "my-release-consul-ui"
  labels:
    app: "consul"
    chart: consul-5.3.6
    release: "my-release"
    heritage: "Tiller"
    component: ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  type: "ClusterIP"
  selector:
    app: "consul"
    chart: consul-5.3.6
    release: "my-release"
    heritage: "Tiller"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "my-release-consul"
  labels:
    app: "consul"
    chart: consul-5.3.6
    release: "my-release"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: consul
      release: "my-release"
  serviceName: "my-release-consul"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "my-release-consul"
      labels:
        app: "consul"
        chart: consul-5.3.6
        release: "my-release"
        heritage: "Tiller"
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "consul"
      containers:
      - name: consul
        #image: "dockerhub.azk8s.cn/bitnami/consul:1.7.1"
        image: "bitnami/consul:1.7.1"
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: http
          containerPort: 8500
        - name: rpc
          containerPort: 8400
        - name: serflan-tcp
          protocol: "TCP"
          containerPort: 8301
        - name: serflan-udp
          protocol: "UDP"
          containerPort: 8301
        - name: server
          containerPort: 8300
        - name: consuldns-tcp
          containerPort: 8600
        - name: consuldns-udp
          protocol: "UDP"
          containerPort: 8600
        resources:
          null
          
        env:
        - name: CONSUL_RETRY_JOIN
          value: "my-release-consul-0.my-release-consul.default.svc"
        - name: CONSUL_DISABLE_KEYRING_FILE
          value: "true"
        - name: CONSUL_BOOTSTRAP_EXPECT
          value: "3"
        - name: CONSUL_BOOTSTRAP_EXPECT
          value: "3"
        - name: CONSUL_RAFT_MULTIPLIER
          value: "1"
        - name: CONSUL_DOMAIN
          value: "consul"
        - name: CONSUL_DATACENTER
          value: "dc1"
        
        
        - name: CONSUL_UI
          value: "true"
        - name: CONSUL_HTTP_PORT_NUMBER
          value: 
        - name: CONSUL_DNS_PORT_NUMBER
          value: "8600"
        - name: CONSUL_RPC_PORT_NUMBER
          value: "8300"
        - name: CONSUL_SERF_LAN_PORT_NUMBER
          value: "8301"
        livenessProbe:
          exec:
            command:
            - consul
            - operator
            - raft
            - list-peers
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - consul
            - members
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        lifecycle:
          preStop:
            exec:
              command:
              - consul
              - leave
        volumeMounts:
        
        - name: cache-volume
          mountPath: /bitnami/consul/data
        
        
      volumes:
      - name: cache-volume
        emptyDir: {}
      
      
  #volumeClaimTemplates:
  #  - metadata:
  #      name: data
  #      annotations:
  #    spec:
  #      accessModes:
  #        - "ReadWriteOnce"
  #      resources:
  #        requests:
  #          storage: "8Gi"
